using PredictiveMaintenanceScheduler.Api.Models;
using PredictiveMaintenanceScheduler.Api.Shared;

namespace PredictiveMaintenanceScheduler.Api.DataStore
{
    public static class MockDataStore
    {
        public static List<User> Users = new List<User>
        {
            new User { ID = 1, Username = "admin", PasswordHash = TokenHelper.HashPassword("admin"), Role = "Admin" },
            new User { ID = 2, Username = "engineer", PasswordHash = TokenHelper.HashPassword("engineer"), Role = "MaintenanceEngineer" }
        };

        public static List<Machine> Machines = new List<Machine>();

        public static List<MachineHealthReading> Readings = new List<MachineHealthReading>();
        public static List<MaintenanceAlert> Alerts = new List<MaintenanceAlert>();
        public static List<MaintenanceSchedule> Schedules = new List<MaintenanceSchedule>();

        static MockDataStore()
        {
            // Seed 14 Machines
            // 3 Robotic Spray Arms
            for (int i = 1; i <= 3; i++) Machines.Add(CreateMachine(i, "Robotic Spray Arm", MachineType.RoboticPaintSprayingArm));
            // 3 Ventilation Motors
            for (int i = 4; i <= 6; i++) Machines.Add(CreateMachine(i, "Ventilation Motor", MachineType.PaintBoothVentilationMotor));
            // 3 Conveyor Belts
            for (int i = 7; i <= 9; i++) Machines.Add(CreateMachine(i, "Conveyor Belt", MachineType.ConveyorBeltSystem));
            // 3 Ovens
            for (int i = 10; i <= 12; i++) Machines.Add(CreateMachine(i, "Paint Curing Oven", MachineType.PaintCuringOven));
            // 2 Pumps
            for (int i = 13; i <= 14; i++) Machines.Add(CreateMachine(i, "Circulation Pump", MachineType.PaintCirculationPump));

            // Seed Maintenance Data (Immediate User Feedback for Admin Page)
            Schedules.Add(new MaintenanceSchedule
            {
                ScheduleID = 1,
                MachineID = 2,
                MachineName = "Robotic Spray Arm 2",
                MaintenanceType = "Repair",
                TaskDescription = "Critical Failure: Vibration > 5mm/s",
                ScheduledDate = DateTime.UtcNow.AddHours(2),
                Status = "Open",
                Priority = "Critical",
                TechnicianNotes = "Generated by System Alert"
            });

            Schedules.Add(new MaintenanceSchedule
            {
                ScheduleID = 2,
                MachineID = 5,
                MachineName = "Ventilation Motor 5",
                MaintenanceType = "Routine",
                TaskDescription = "Weekly Inspection",
                ScheduledDate = DateTime.UtcNow.AddDays(1),
                Status = "Open",
                Priority = "Medium",
                TechnicianNotes = "Check airflow filters"
            });

            Schedules.Add(new MaintenanceSchedule
            {
                ScheduleID = 3,
                MachineID = 9,
                MachineName = "Conveyor Belt 9",
                MaintenanceType = "Inspection",
                TaskDescription = "Belt Tension Check",
                ScheduledDate = DateTime.UtcNow.AddDays(-2),
                Status = "Completed",
                Priority = "High",
                TechnicianNotes = "Belt retensioned. All safe.",
                CompletedDate = DateTime.UtcNow.AddDays(-2).AddHours(1)
            });
        }

        private static Machine CreateMachine(int id, string baseName, MachineType type)
        {
             return new Machine
             {
                 MachineID = id,
                 MachineName = $"{baseName} {id}",
                 Type = type.ToString(), // Storing as string to match Model definition but using Enum for logic
                 Location = "Zone A",
                 InstallDate = DateTime.UtcNow.AddMonths(-new Random().Next(1, 24)),
                 LastMaintenanceDate = DateTime.UtcNow.AddDays(-new Random().Next(1, 30)),
                 Status = "Safe",
                 HealthScore = 100
             };
        }
    }
}
