using PredictiveMaintenanceScheduler.Api.DataStore;
using PredictiveMaintenanceScheduler.Api.Models;
using PredictiveMaintenanceScheduler.Api.Shared;

namespace PredictiveMaintenanceScheduler.Api.Services
{
    public class AlertService
    {
        public void ProcessHealthStatus(int machineId, string status, string message)
        {
            if (status == "Critical")
            {
                // Create Alert
                var alert = new MaintenanceAlert
                {
                    AlertID = MockDataStore.Alerts.Count + 1,
                    MachineID = machineId,
                    Severity = "Critical",
                    Message = message,
                    Timestamp = DateTime.UtcNow,
                    IsAcknowledged = false
                };
                MockDataStore.Alerts.Add(alert);

                // Create Schedule (Automated)
                // Check if already open schedule exists
                var existing = MockDataStore.Schedules.Any(s => s.MachineID == machineId && s.Status == "Open");
                if (!existing)
                {
                     // Fetch Machine Name for consistency
                    var machine = MockDataStore.Machines.FirstOrDefault(m => m.MachineID == machineId);

                    MockDataStore.Schedules.Add(new MaintenanceSchedule
                    {
                        ScheduleID = MockDataStore.Schedules.Count + 1,
                        MachineID = machineId,
                        MachineName = machine?.MachineName ?? "Unknown",
                        MaintenanceType = "Repair", // Default for critical alert
                        TaskDescription = $"Auto-Scheduled: {message}",
                        ScheduledDate = DateTime.UtcNow.AddHours(4), // Urgent
                        Priority = "Critical",
                        Status = "Open",
                        TechnicianNotes = "Generated by System Alert"
                    });
                }
            }
            else if (status == "Warning")
            {
                var alert = new MaintenanceAlert
                {
                    AlertID = MockDataStore.Alerts.Count + 1,
                    MachineID = machineId,
                    Severity = "Warning",
                    Message = message,
                    Timestamp = DateTime.UtcNow,
                    IsAcknowledged = false
                };
                MockDataStore.Alerts.Add(alert);
            }
        }
        
        public IEnumerable<MaintenanceAlert> GetAlerts() => MockDataStore.Alerts.OrderByDescending(x => x.Timestamp);
    }
}
